[project]
name = "union-militaty-lawyers-bot"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.22.0",
    "black>=25.9.0",
    "pydantic>=2.11.10",
    "python-dotenv>=1.2.1",
    "pygithub>=2.4.1",
]
